# -*- coding: utf-8 -*-
"""Biofuel Comparison

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HKV-Hvij3BRjyuvBJHHHs3kTSHSBwnER
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv("fuel_molecules.csv")
print(df)

plt.scatter(df["Carbons"], df["BoilingPoint"])
plt.xlabel("Carbon Atoms")
plt.ylabel("Boiling Point (°C)")
plt.title("Carbon Atoms vs. Boiling Point")
for i, name in enumerate(df["Molecule"]):
    plt.annotate(name, (df["Carbons"][i], df["BoilingPoint"][i]))
plt.show()

plt.scatter(df["MolecularWeight"], df["BoilingPoint"])
plt.xlabel("Molecular Weight (g/mol)")
plt.ylabel("Boiling Point (°C)")
plt.title("Molecular Weight vs. Boiling Point")
for i, name in enumerate(df["Molecule"]):
    plt.annotate(name, (df["MolecularWeight"][i], df["BoilingPoint"][i]))
plt.show()

pairs = ["Ethane", "Ethanol", "Butane", "Butanol"]
subset = df[df["Molecule"].isin(pairs)]

colors = ["orange" if ox == 1 else "blue" for ox in subset["Oxygen"]]
plt.bar(subset["Molecule"], subset["BoilingPoint"], color=colors)
plt.xlabel("Molecule")
plt.ylabel("Boiling Point (°C)")
plt.title("Hydrocarbon vs. Alcohol Boiling Points")
plt.show()